window.SEED_DATA = {
  "generatedAt": "2026-06-21T18:45:13.752876",
  "sourceFile": "Financeiro - 2026(1).xlsx",
  "meses": [
    "janeiro",
    "fevereiro",
    "março",
    "abril",
    "maio",
    "junho",
    "julho",
    "agosto",
    "setembro",
    "outubro",
    "novembro",
    "dezembro"
  ],
  "fixas": [
    {
      "nome": "Caixa",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 566.0,
        "junho": 560.0,
        "julho": 560.0,
        "agosto": 560.0,
        "setembro": 560.0,
        "outubro": 560.0,
        "novembro": 560.0,
        "dezembro": 560.0
      }
    },
    {
      "nome": "Condomínio",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 152.0,
        "junho": 152.0,
        "julho": 152.0,
        "agosto": 152.0,
        "setembro": 152.0,
        "outubro": 152.0,
        "novembro": 152.0,
        "dezembro": 152.0
      }
    },
    {
      "nome": "Crédito celular",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 30.0,
        "junho": 90.0,
        "julho": 90.0,
        "agosto": 70.0,
        "setembro": 70.0,
        "outubro": 70.0,
        "novembro": 70.0,
        "dezembro": 70.0
      }
    },
    {
      "nome": "Combustível",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 1200.0,
        "junho": 1200.0,
        "julho": 1200.0,
        "agosto": 1200.0,
        "setembro": 1200.0,
        "outubro": 1200.0,
        "novembro": 1200.0,
        "dezembro": 1200.0
      }
    },
    {
      "nome": "Parcela do carro",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 2321.15,
        "junho": 2321.15,
        "julho": 2321.15,
        "agosto": 2321.15,
        "setembro": 2321.15,
        "outubro": 2321.15,
        "novembro": 2321.15,
        "dezembro": 2321.15
      }
    },
    {
      "nome": "Água mineral",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 96.0,
        "junho": 96.0,
        "julho": 96.0,
        "agosto": 96.0,
        "setembro": 96.0,
        "outubro": 96.0,
        "novembro": 96.0,
        "dezembro": 96.0
      }
    },
    {
      "nome": "Gás",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 100.0,
        "junho": 100.0,
        "julho": 100.0,
        "agosto": 100.0,
        "setembro": 100.0,
        "outubro": 100.0,
        "novembro": 100.0,
        "dezembro": 100.0
      }
    },
    {
      "nome": "Celpe",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 300.0,
        "junho": 300.0,
        "julho": 300.0,
        "agosto": 300.0,
        "setembro": 300.0,
        "outubro": 300.0,
        "novembro": 300.0,
        "dezembro": 300.0
      }
    },
    {
      "nome": "Alimentação",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 3400.0,
        "junho": 2900.0,
        "julho": 2900.0,
        "agosto": 3400.0,
        "setembro": 2900.0,
        "outubro": 3400.0,
        "novembro": 2900.0,
        "dezembro": 2900.0
      }
    },
    {
      "nome": "São Gabriel",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 33.0,
        "junho": 33.0,
        "julho": 33.0,
        "agosto": 33.0,
        "setembro": 33.0,
        "outubro": 33.0,
        "novembro": 33.0,
        "dezembro": 33.0
      }
    },
    {
      "nome": "Select",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 0.0,
        "junho": 0.0,
        "julho": 600.0,
        "agosto": 600.0,
        "setembro": 600.0,
        "outubro": 600.0,
        "novembro": 600.0,
        "dezembro": 600.0
      }
    },
    {
      "nome": "Unimed",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 774.68,
        "junho": 774.68,
        "julho": 774.68,
        "agosto": 774.68,
        "setembro": 774.68,
        "outubro": 774.68,
        "novembro": 774.68,
        "dezembro": 774.68
      }
    },
    {
      "nome": "Antena",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 20.0,
        "junho": 20.0,
        "julho": 20.0,
        "agosto": 20.0,
        "setembro": 20.0,
        "outubro": 20.0,
        "novembro": 20.0,
        "dezembro": 20.0
      }
    },
    {
      "nome": "Mainha",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 350.0,
        "junho": 350.0,
        "julho": 350.0,
        "agosto": 350.0,
        "setembro": 350.0,
        "outubro": 350.0,
        "novembro": 350.0,
        "dezembro": 350.0
      }
    },
    {
      "nome": "Internet",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 80.0,
        "junho": 80.0,
        "julho": 80.0,
        "agosto": 80.0,
        "setembro": 80.0,
        "outubro": 80.0,
        "novembro": 80.0,
        "dezembro": 80.0
      }
    }
  ],
  "variaveis": [
    {
      "nome": "Rafaela",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 150.0,
        "junho": 150.0,
        "julho": 150.0,
        "agosto": 150.0,
        "setembro": 150.0,
        "outubro": 150.0,
        "novembro": 150.0,
        "dezembro": 150.0
      }
    },
    {
      "nome": "lanche",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 200.0,
        "junho": 200.0,
        "julho": 200.0,
        "agosto": 200.0,
        "setembro": 200.0,
        "outubro": 200.0,
        "novembro": 200.0,
        "dezembro": 200.0
      }
    },
    {
      "nome": "Felipe",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 200.0,
        "junho": 200.0,
        "julho": 200.0,
        "agosto": 200.0,
        "setembro": 200.0,
        "outubro": 200.0,
        "novembro": 200.0,
        "dezembro": 200.0
      }
    },
    {
      "nome": "Spotify",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 11.6,
        "junho": 11.6,
        "julho": 11.6,
        "agosto": 11.6,
        "setembro": 11.6,
        "outubro": 11.6,
        "novembro": 11.6,
        "dezembro": 11.6
      }
    },
    {
      "nome": "Sobral",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 55.0,
        "junho": 55.0,
        "julho": 55.0,
        "agosto": 55.0,
        "setembro": 55.0,
        "outubro": 55.0,
        "novembro": 0.0,
        "dezembro": 0.0
      }
    },
    {
      "nome": "Cartões",
      "valores": {
        "janeiro": 0,
        "fevereiro": 0,
        "março": 0,
        "abril": 0,
        "maio": 4470.45,
        "junho": 4049.62,
        "julho": 4071.15,
        "agosto": 1664.22,
        "setembro": 1352.49,
        "outubro": 1291.29,
        "novembro": 1291.29,
        "dezembro": 1291.29
      }
    }
  ],
  "orcamento": [
    {
      "mes": "janeiro",
      "receitas": 0,
      "receitas_felipe": 0,
      "receitas_rafaela": 0,
      "despesas_planilha": 0,
      "despesas_calculadas": 143.35,
      "diferenca": 0,
      "despesas": 143.35,
      "fixas": 0,
      "variaveis": 0,
      "cartoes": 143.35,
      "saldo": -143.35,
      "modo": "calculado"
    },
    {
      "mes": "fevereiro",
      "receitas": 0,
      "receitas_felipe": 0,
      "receitas_rafaela": 0,
      "despesas_planilha": 0,
      "despesas_calculadas": 245.75,
      "diferenca": 0,
      "despesas": 245.75,
      "fixas": 0,
      "variaveis": 0,
      "cartoes": 245.75,
      "saldo": -245.75,
      "modo": "calculado"
    },
    {
      "mes": "março",
      "receitas": 0,
      "receitas_felipe": 0,
      "receitas_rafaela": 0,
      "despesas_planilha": 0,
      "despesas_calculadas": 455.69,
      "diferenca": 0,
      "despesas": 455.69,
      "fixas": 0,
      "variaveis": 0,
      "cartoes": 455.69,
      "saldo": -455.69,
      "modo": "calculado"
    },
    {
      "mes": "abril",
      "receitas": 0,
      "receitas_felipe": 0,
      "receitas_rafaela": 0,
      "despesas_planilha": 0,
      "despesas_calculadas": 450.83,
      "diferenca": 0,
      "despesas": 450.83,
      "fixas": 0,
      "variaveis": 0,
      "cartoes": 450.83,
      "saldo": -450.83,
      "modo": "calculado"
    },
    {
      "mes": "maio",
      "receitas": 8700.0,
      "receitas_felipe": 6000.0,
      "receitas_rafaela": 2700.0,
      "despesas_planilha": 14509.88,
      "despesas_calculadas": 14909.65,
      "diferenca": 399.77,
      "despesas": 14509.88,
      "fixas": 9422.83,
      "variaveis": 616.6,
      "cartoes": 4870.22,
      "saldo": -5809.88,
      "modo": "planilha"
    },
    {
      "mes": "junho",
      "receitas": 22092.7,
      "receitas_felipe": 19392.7,
      "receitas_rafaela": 2700.0,
      "despesas_planilha": 13643.05,
      "despesas_calculadas": 13924.49,
      "diferenca": 281.44,
      "despesas": 13643.05,
      "fixas": 8976.83,
      "variaveis": 616.6,
      "cartoes": 4331.06,
      "saldo": 8449.65,
      "modo": "planilha"
    },
    {
      "mes": "julho",
      "receitas": 17175.4,
      "receitas_felipe": 14475.4,
      "receitas_rafaela": 2700.0,
      "despesas_planilha": 14264.58,
      "despesas_calculadas": 14346.56,
      "diferenca": 81.98,
      "despesas": 14264.58,
      "fixas": 9576.83,
      "variaveis": 616.6,
      "cartoes": 4153.13,
      "saldo": 2910.82,
      "modo": "planilha"
    },
    {
      "mes": "agosto",
      "receitas": 17175.4,
      "receitas_felipe": 14475.4,
      "receitas_rafaela": 2700.0,
      "despesas_planilha": 12337.65,
      "despesas_calculadas": 12684.64,
      "diferenca": 346.99,
      "despesas": 12337.65,
      "fixas": 10056.83,
      "variaveis": 616.6,
      "cartoes": 2011.21,
      "saldo": 4837.75,
      "modo": "planilha"
    },
    {
      "mes": "setembro",
      "receitas": 17175.4,
      "receitas_felipe": 14475.4,
      "receitas_rafaela": 2700.0,
      "despesas_planilha": 11525.92,
      "despesas_calculadas": 11872.91,
      "diferenca": 346.99,
      "despesas": 11525.92,
      "fixas": 9556.83,
      "variaveis": 616.6,
      "cartoes": 1699.48,
      "saldo": 5649.48,
      "modo": "planilha"
    },
    {
      "mes": "outubro",
      "receitas": 17175.4,
      "receitas_felipe": 14475.4,
      "receitas_rafaela": 2700.0,
      "despesas_planilha": 11964.72,
      "despesas_calculadas": 12311.71,
      "diferenca": 346.99,
      "despesas": 11964.72,
      "fixas": 10056.83,
      "variaveis": 616.6,
      "cartoes": 1638.28,
      "saldo": 5210.68,
      "modo": "planilha"
    },
    {
      "mes": "novembro",
      "receitas": 17175.4,
      "receitas_felipe": 14475.4,
      "receitas_rafaela": 2700.0,
      "despesas_planilha": 11409.72,
      "despesas_calculadas": 11712.18,
      "diferenca": 302.46,
      "despesas": 11409.72,
      "fixas": 9556.83,
      "variaveis": 561.6,
      "cartoes": 1593.75,
      "saldo": 5765.68,
      "modo": "planilha"
    },
    {
      "mes": "dezembro",
      "receitas": 17175.4,
      "receitas_felipe": 14475.4,
      "receitas_rafaela": 2700.0,
      "despesas_planilha": 11409.72,
      "despesas_calculadas": 11813.97,
      "diferenca": 404.25,
      "despesas": 11409.72,
      "fixas": 9556.83,
      "variaveis": 561.6,
      "cartoes": 1695.54,
      "saldo": 5765.68,
      "modo": "planilha"
    }
  ],
  "comprasCartao": [
    {
      "id": "import-1",
      "cartao": "Nubank Felipe",
      "empresa": "Natura",
      "empresaNorm": "natura",
      "mes": "maio",
      "valor": 32.56,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-2",
      "cartao": "Nubank Felipe",
      "empresa": "Natura",
      "empresaNorm": "natura",
      "mes": "junho",
      "valor": 32.56,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-3",
      "cartao": "Nubank Felipe",
      "empresa": "gympass/academia",
      "empresaNorm": "gympass/academia",
      "mes": "maio",
      "valor": 79.9,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-4",
      "cartao": "Nubank Felipe",
      "empresa": "gympass/academia",
      "empresaNorm": "gympass/academia",
      "mes": "junho",
      "valor": 79.9,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-5",
      "cartao": "Nubank Felipe",
      "empresa": "gympass/academia",
      "empresaNorm": "gympass/academia",
      "mes": "julho",
      "valor": 79.9,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-6",
      "cartao": "Nubank Felipe",
      "empresa": "gympass/academia",
      "empresaNorm": "gympass/academia",
      "mes": "agosto",
      "valor": 79.9,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-7",
      "cartao": "Nubank Felipe",
      "empresa": "gympass/academia",
      "empresaNorm": "gympass/academia",
      "mes": "setembro",
      "valor": 79.9,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-8",
      "cartao": "Nubank Felipe",
      "empresa": "gympass/academia",
      "empresaNorm": "gympass/academia",
      "mes": "outubro",
      "valor": 79.9,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-9",
      "cartao": "Nubank Felipe",
      "empresa": "gympass/academia",
      "empresaNorm": "gympass/academia",
      "mes": "novembro",
      "valor": 79.9,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-10",
      "cartao": "Nubank Felipe",
      "empresa": "gympass/academia",
      "empresaNorm": "gympass/academia",
      "mes": "dezembro",
      "valor": 79.9,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-11",
      "cartao": "Nubank Felipe",
      "empresa": "Cerpe",
      "empresaNorm": "cerpe",
      "mes": "maio",
      "valor": 19.55,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-12",
      "cartao": "Nubank Felipe",
      "empresa": "Seguro da moto",
      "empresaNorm": "seguro da moto",
      "mes": "maio",
      "valor": 56.72,
      "categoria": "Transporte",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-13",
      "cartao": "Nubank Felipe",
      "empresa": "Seguro da moto",
      "empresaNorm": "seguro da moto",
      "mes": "junho",
      "valor": 56.72,
      "categoria": "Transporte",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-14",
      "cartao": "Nubank Felipe",
      "empresa": "Seguro da moto",
      "empresaNorm": "seguro da moto",
      "mes": "julho",
      "valor": 56.72,
      "categoria": "Transporte",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-15",
      "cartao": "Nubank Felipe",
      "empresa": "Seguro da moto",
      "empresaNorm": "seguro da moto",
      "mes": "agosto",
      "valor": 56.72,
      "categoria": "Transporte",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-16",
      "cartao": "Nubank Felipe",
      "empresa": "Seguro da moto",
      "empresaNorm": "seguro da moto",
      "mes": "setembro",
      "valor": 56.72,
      "categoria": "Transporte",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-17",
      "cartao": "Nubank Felipe",
      "empresa": "Seguro da moto",
      "empresaNorm": "seguro da moto",
      "mes": "outubro",
      "valor": 56.72,
      "categoria": "Transporte",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-18",
      "cartao": "Nubank Felipe",
      "empresa": "Seguro da moto",
      "empresaNorm": "seguro da moto",
      "mes": "novembro",
      "valor": 56.72,
      "categoria": "Transporte",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-19",
      "cartao": "Nubank Felipe",
      "empresa": "Seguro da moto",
      "empresaNorm": "seguro da moto",
      "mes": "dezembro",
      "valor": 56.72,
      "categoria": "Transporte",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-20",
      "cartao": "Nubank Felipe",
      "empresa": "Loja Militar",
      "empresaNorm": "loja militar",
      "mes": "maio",
      "valor": 53.34,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-21",
      "cartao": "Nubank Felipe",
      "empresa": "Loja Militar",
      "empresaNorm": "loja militar",
      "mes": "junho",
      "valor": 53.33,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-22",
      "cartao": "Nubank Felipe",
      "empresa": "Loja Militar",
      "empresaNorm": "loja militar",
      "mes": "julho",
      "valor": 53.33,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-23",
      "cartao": "Nubank Felipe",
      "empresa": "Mercado livre",
      "empresaNorm": "mercado livre",
      "mes": "maio",
      "valor": 29.12,
      "categoria": "Feira",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-24",
      "cartao": "Nubank Felipe",
      "empresa": "Mercado livre",
      "empresaNorm": "mercado livre",
      "mes": "junho",
      "valor": 29.12,
      "categoria": "Feira",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-25",
      "cartao": "Nubank Felipe",
      "empresa": "Mercado livre",
      "empresaNorm": "mercado livre",
      "mes": "julho",
      "valor": 29.09,
      "categoria": "Feira",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-26",
      "cartao": "Nubank Felipe",
      "empresa": "Figurinha",
      "empresaNorm": "figurinha",
      "mes": "julho",
      "valor": 112.5,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-27",
      "cartao": "Nubank Felipe",
      "empresa": "Banca Santana",
      "empresaNorm": "banca santana",
      "mes": "julho",
      "valor": 34.99,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-28",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "julho",
      "valor": 9.58,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-29",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "agosto",
      "valor": 9.58,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-30",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "setembro",
      "valor": 9.58,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-31",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "outubro",
      "valor": 9.58,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-32",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "novembro",
      "valor": 9.58,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-33",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "dezembro",
      "valor": 9.58,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-34",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "julho",
      "valor": 17.4,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-35",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "agosto",
      "valor": 17.4,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-36",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "setembro",
      "valor": 17.4,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-37",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "outubro",
      "valor": 17.4,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-38",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "novembro",
      "valor": 17.4,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-39",
      "cartao": "Nubank Felipe",
      "empresa": "Shopee",
      "empresaNorm": "shopee",
      "mes": "dezembro",
      "valor": 17.4,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-40",
      "cartao": "Nubank Felipe",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "maio",
      "valor": 52.26,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-41",
      "cartao": "Nubank Felipe",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "junho",
      "valor": 52.26,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-42",
      "cartao": "Nubank Felipe",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "julho",
      "valor": 52.22,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-43",
      "cartao": "Nubank Felipe",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "agosto",
      "valor": 52.26,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-44",
      "cartao": "Nubank Felipe",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "setembro",
      "valor": 52.26,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-45",
      "cartao": "Nubank Felipe",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "outubro",
      "valor": 52.26,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-46",
      "cartao": "Nubank Felipe",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "novembro",
      "valor": 52.26,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-47",
      "cartao": "Nubank Felipe",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "dezembro",
      "valor": 52.26,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-48",
      "cartao": "Nubank Felipe",
      "empresa": "Ri happy",
      "empresaNorm": "ri happy",
      "mes": "maio",
      "valor": 30.03,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-49",
      "cartao": "Nubank Felipe",
      "empresa": "Ri happy",
      "empresaNorm": "ri happy",
      "mes": "junho",
      "valor": 30.03,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-50",
      "cartao": "Nubank Felipe",
      "empresa": "Ri happy",
      "empresaNorm": "ri happy",
      "mes": "julho",
      "valor": 29.99,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-51",
      "cartao": "Nubank Felipe",
      "empresa": "Ri happy",
      "empresaNorm": "ri happy",
      "mes": "agosto",
      "valor": 30.03,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-52",
      "cartao": "Nubank Felipe",
      "empresa": "Farmácia",
      "empresaNorm": "farmacia",
      "mes": "maio",
      "valor": 26.25,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-53",
      "cartao": "Nubank Felipe",
      "empresa": "Farmácia",
      "empresaNorm": "farmacia",
      "mes": "junho",
      "valor": 26.25,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-54",
      "cartao": "Nubank Felipe",
      "empresa": "Farmácia",
      "empresaNorm": "farmacia",
      "mes": "julho",
      "valor": 26.25,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-55",
      "cartao": "Nubank Felipe",
      "empresa": "Farmácia",
      "empresaNorm": "farmacia",
      "mes": "agosto",
      "valor": 26.25,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-56",
      "cartao": "Nubank Felipe",
      "empresa": "Farmácia",
      "empresaNorm": "farmacia",
      "mes": "setembro",
      "valor": 26.25,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-57",
      "cartao": "Nubank Felipe",
      "empresa": "Farmácia",
      "empresaNorm": "farmacia",
      "mes": "outubro",
      "valor": 26.25,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-58",
      "cartao": "Nubank Felipe",
      "empresa": "Farmácia",
      "empresaNorm": "farmacia",
      "mes": "novembro",
      "valor": 26.25,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-59",
      "cartao": "Nubank Felipe",
      "empresa": "Farmácia",
      "empresaNorm": "farmacia",
      "mes": "dezembro",
      "valor": 26.25,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-60",
      "cartao": "Nubank Felipe",
      "empresa": "Lalelilo",
      "empresaNorm": "lalelilo",
      "mes": "maio",
      "valor": 84.8,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-61",
      "cartao": "Nubank Felipe",
      "empresa": "Tinta impressora",
      "empresaNorm": "tinta impressora",
      "mes": "maio",
      "valor": 12.59,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-62",
      "cartao": "Nubank Felipe",
      "empresa": "Tinta impressora",
      "empresaNorm": "tinta impressora",
      "mes": "junho",
      "valor": 12.59,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-63",
      "cartao": "Nubank Felipe",
      "empresa": "Tinta impressora",
      "empresaNorm": "tinta impressora",
      "mes": "julho",
      "valor": 12.59,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-64",
      "cartao": "Nubank Felipe",
      "empresa": "Tinta impressora",
      "empresaNorm": "tinta impressora",
      "mes": "agosto",
      "valor": 12.59,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-65",
      "cartao": "Nubank Felipe",
      "empresa": "Tinta impressora",
      "empresaNorm": "tinta impressora",
      "mes": "setembro",
      "valor": 12.59,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-66",
      "cartao": "Nubank Felipe",
      "empresa": "Tinta impressora",
      "empresaNorm": "tinta impressora",
      "mes": "outubro",
      "valor": 12.59,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-67",
      "cartao": "Nubank Felipe",
      "empresa": "Tinta impressora",
      "empresaNorm": "tinta impressora",
      "mes": "novembro",
      "valor": 12.59,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-68",
      "cartao": "Nubank Felipe",
      "empresa": "Tinta impressora",
      "empresaNorm": "tinta impressora",
      "mes": "dezembro",
      "valor": 12.59,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-69",
      "cartao": "Nubank Felipe",
      "empresa": "Mercado livre",
      "empresaNorm": "mercado livre",
      "mes": "maio",
      "valor": 22.21,
      "categoria": "Feira",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-70",
      "cartao": "Nubank Felipe",
      "empresa": "Mercado livre",
      "empresaNorm": "mercado livre",
      "mes": "junho",
      "valor": 22.21,
      "categoria": "Feira",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-71",
      "cartao": "Nubank Felipe",
      "empresa": "Mercado livre",
      "empresaNorm": "mercado livre",
      "mes": "julho",
      "valor": 22.21,
      "categoria": "Feira",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-72",
      "cartao": "Nubank Felipe",
      "empresa": "Mercado livre",
      "empresaNorm": "mercado livre",
      "mes": "agosto",
      "valor": 22.21,
      "categoria": "Feira",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-73",
      "cartao": "Nubank Felipe",
      "empresa": "Mercado livre",
      "empresaNorm": "mercado livre",
      "mes": "setembro",
      "valor": 22.21,
      "categoria": "Feira",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-74",
      "cartao": "Nubank Felipe",
      "empresa": "Ortobom",
      "empresaNorm": "ortobom",
      "mes": "maio",
      "valor": 33.2,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-75",
      "cartao": "Nubank Felipe",
      "empresa": "Ortobom",
      "empresaNorm": "ortobom",
      "mes": "junho",
      "valor": 33.2,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-76",
      "cartao": "Nubank Felipe",
      "empresa": "Ortobom",
      "empresaNorm": "ortobom",
      "mes": "julho",
      "valor": 33.2,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-77",
      "cartao": "Nubank Felipe",
      "empresa": "Ar condicionado",
      "empresaNorm": "ar condicionado",
      "mes": "maio",
      "valor": 160.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-78",
      "cartao": "Nubank Felipe",
      "empresa": "Ar condicionado",
      "empresaNorm": "ar condicionado",
      "mes": "junho",
      "valor": 160.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-79",
      "cartao": "Nubank Felipe",
      "empresa": "Ar condicionado",
      "empresaNorm": "ar condicionado",
      "mes": "julho",
      "valor": 160.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-80",
      "cartao": "Nubank Felipe",
      "empresa": "Ar condicionado",
      "empresaNorm": "ar condicionado",
      "mes": "agosto",
      "valor": 160.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-81",
      "cartao": "Nubank Felipe",
      "empresa": "Ar condicionado",
      "empresaNorm": "ar condicionado",
      "mes": "setembro",
      "valor": 160.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-82",
      "cartao": "Nubank Felipe",
      "empresa": "Ar condicionado",
      "empresaNorm": "ar condicionado",
      "mes": "outubro",
      "valor": 160.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-83",
      "cartao": "Nubank Felipe",
      "empresa": "Ar condicionado",
      "empresaNorm": "ar condicionado",
      "mes": "novembro",
      "valor": 160.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-84",
      "cartao": "Nubank Felipe",
      "empresa": "Ar condicionado",
      "empresaNorm": "ar condicionado",
      "mes": "dezembro",
      "valor": 160.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-85",
      "cartao": "Nubank Felipe",
      "empresa": "Império Movéis",
      "empresaNorm": "imperio moveis",
      "mes": "maio",
      "valor": 23.96,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-86",
      "cartao": "Nubank Felipe",
      "empresa": "tablet",
      "empresaNorm": "tablet",
      "mes": "maio",
      "valor": 241.58,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-87",
      "cartao": "Nubank Felipe",
      "empresa": "tablet",
      "empresaNorm": "tablet",
      "mes": "junho",
      "valor": 241.58,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-88",
      "cartao": "Nubank Felipe",
      "empresa": "tablet",
      "empresaNorm": "tablet",
      "mes": "julho",
      "valor": 241.58,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-89",
      "cartao": "Nubank Felipe",
      "empresa": "tablet",
      "empresaNorm": "tablet",
      "mes": "agosto",
      "valor": 241.58,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-90",
      "cartao": "Nubank Felipe",
      "empresa": "Caroatá",
      "empresaNorm": "caroata",
      "mes": "maio",
      "valor": 49.12,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-91",
      "cartao": "Nubank Felipe",
      "empresa": "Ri happy",
      "empresaNorm": "ri happy",
      "mes": "maio",
      "valor": 38.99,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-92",
      "cartao": "Nubank Felipe",
      "empresa": "Ri happy",
      "empresaNorm": "ri happy",
      "mes": "junho",
      "valor": 38.99,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-93",
      "cartao": "Nubank Felipe",
      "empresa": "Ri happy",
      "empresaNorm": "ri happy",
      "mes": "julho",
      "valor": 38.99,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-94",
      "cartao": "Nubank Felipe",
      "empresa": "Ri happy",
      "empresaNorm": "ri happy",
      "mes": "agosto",
      "valor": 38.99,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-95",
      "cartao": "Nubank Felipe",
      "empresa": "Ri happy",
      "empresaNorm": "ri happy",
      "mes": "setembro",
      "valor": 38.99,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-96",
      "cartao": "Nubank Felipe",
      "empresa": "óculos de sol",
      "empresaNorm": "oculos de sol",
      "mes": "maio",
      "valor": 49.98,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-97",
      "cartao": "Nubank Felipe",
      "empresa": "óculos de sol",
      "empresaNorm": "oculos de sol",
      "mes": "junho",
      "valor": 49.98,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-98",
      "cartao": "Nubank Felipe",
      "empresa": "Barbeiro",
      "empresaNorm": "barbeiro",
      "mes": "maio",
      "valor": 209.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-99",
      "cartao": "Nubank Felipe",
      "empresa": "Barbeiro",
      "empresaNorm": "barbeiro",
      "mes": "junho",
      "valor": 209.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-100",
      "cartao": "Nubank Felipe",
      "empresa": "Barbeiro",
      "empresaNorm": "barbeiro",
      "mes": "julho",
      "valor": 209.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-101",
      "cartao": "Nubank Felipe",
      "empresa": "Barbeiro",
      "empresaNorm": "barbeiro",
      "mes": "agosto",
      "valor": 209.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-102",
      "cartao": "Nubank Felipe",
      "empresa": "Barbeiro",
      "empresaNorm": "barbeiro",
      "mes": "setembro",
      "valor": 209.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-103",
      "cartao": "Nubank Felipe",
      "empresa": "Barbeiro",
      "empresaNorm": "barbeiro",
      "mes": "outubro",
      "valor": 209.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-104",
      "cartao": "Nubank Felipe",
      "empresa": "Barbeiro",
      "empresaNorm": "barbeiro",
      "mes": "novembro",
      "valor": 209.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-105",
      "cartao": "Nubank Felipe",
      "empresa": "Barbeiro",
      "empresaNorm": "barbeiro",
      "mes": "dezembro",
      "valor": 209.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-106",
      "cartao": "Nubank Felipe",
      "empresa": "Assinaturas",
      "empresaNorm": "assinaturas",
      "mes": "maio",
      "valor": 54.89,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-107",
      "cartao": "Nubank Felipe",
      "empresa": "Assinaturas",
      "empresaNorm": "assinaturas",
      "mes": "junho",
      "valor": 54.89,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-108",
      "cartao": "Nubank Felipe",
      "empresa": "Assinaturas",
      "empresaNorm": "assinaturas",
      "mes": "julho",
      "valor": 54.89,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-109",
      "cartao": "Nubank Felipe",
      "empresa": "Assinaturas",
      "empresaNorm": "assinaturas",
      "mes": "agosto",
      "valor": 54.89,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-110",
      "cartao": "Nubank Felipe",
      "empresa": "Assinaturas",
      "empresaNorm": "assinaturas",
      "mes": "setembro",
      "valor": 54.89,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-111",
      "cartao": "Nubank Felipe",
      "empresa": "Assinaturas",
      "empresaNorm": "assinaturas",
      "mes": "outubro",
      "valor": 54.89,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-112",
      "cartao": "Nubank Felipe",
      "empresa": "Assinaturas",
      "empresaNorm": "assinaturas",
      "mes": "novembro",
      "valor": 54.89,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-113",
      "cartao": "Nubank Felipe",
      "empresa": "Assinaturas",
      "empresaNorm": "assinaturas",
      "mes": "dezembro",
      "valor": 54.89,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-114",
      "cartao": "Nubank Rafaela",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "dezembro",
      "valor": 23.89,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-115",
      "cartao": "Nubank Rafaela",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "janeiro",
      "valor": 23.89,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-116",
      "cartao": "Nubank Rafaela",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "fevereiro",
      "valor": 23.89,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-117",
      "cartao": "Nubank Rafaela",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "março",
      "valor": 23.89,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-118",
      "cartao": "Nubank Rafaela",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "abril",
      "valor": 23.89,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-119",
      "cartao": "Nubank Rafaela",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "maio",
      "valor": 23.89,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-120",
      "cartao": "Nubank Rafaela",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "junho",
      "valor": 23.89,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-121",
      "cartao": "Nubank Rafaela",
      "empresa": "Farda Yuri",
      "empresaNorm": "farda yuri",
      "mes": "fevereiro",
      "valor": 44.0,
      "categoria": "Educação",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-122",
      "cartao": "Nubank Rafaela",
      "empresa": "Farda Yuri",
      "empresaNorm": "farda yuri",
      "mes": "março",
      "valor": 44.0,
      "categoria": "Educação",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-123",
      "cartao": "Nubank Rafaela",
      "empresa": "Game station",
      "empresaNorm": "game station",
      "mes": "abril",
      "valor": 40.0,
      "categoria": "Lazer",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-124",
      "cartao": "Nubank Rafaela",
      "empresa": "Game station",
      "empresaNorm": "game station",
      "mes": "maio",
      "valor": 40.0,
      "categoria": "Lazer",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-125",
      "cartao": "Nubank Rafaela",
      "empresa": "Balm barba",
      "empresaNorm": "balm barba",
      "mes": "março",
      "valor": 26.49,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-126",
      "cartao": "Nubank Rafaela",
      "empresa": "Balm barba",
      "empresaNorm": "balm barba",
      "mes": "abril",
      "valor": 26.49,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-127",
      "cartao": "Nubank Rafaela",
      "empresa": "C&A",
      "empresaNorm": "c&a",
      "mes": "abril",
      "valor": 163.32,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-128",
      "cartao": "Nubank Rafaela",
      "empresa": "C&A",
      "empresaNorm": "c&a",
      "mes": "maio",
      "valor": 163.32,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-129",
      "cartao": "Nubank Rafaela",
      "empresa": "C&A",
      "empresaNorm": "c&a",
      "mes": "junho",
      "valor": 163.32,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-130",
      "cartao": "Nubank Rafaela",
      "empresa": "Casa da moda",
      "empresaNorm": "casa da moda",
      "mes": "março",
      "valor": 22.0,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-131",
      "cartao": "Nubank Rafaela",
      "empresa": "Casa da moda",
      "empresaNorm": "casa da moda",
      "mes": "abril",
      "valor": 22.0,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-132",
      "cartao": "Nubank Rafaela",
      "empresa": "Casa da moda",
      "empresaNorm": "casa da moda",
      "mes": "maio",
      "valor": 43.33,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-133",
      "cartao": "Nubank Rafaela",
      "empresa": "Máscara de Yuri",
      "empresaNorm": "mascara de yuri",
      "mes": "março",
      "valor": 27.5,
      "categoria": "Educação",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-134",
      "cartao": "Nubank Rafaela",
      "empresa": "Máscara de Yuri",
      "empresaNorm": "mascara de yuri",
      "mes": "abril",
      "valor": 27.5,
      "categoria": "Educação",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-135",
      "cartao": "Nubank Rafaela",
      "empresa": "Havaianas",
      "empresaNorm": "havaianas",
      "mes": "maio",
      "valor": 35.0,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-136",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "fevereiro",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-137",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "março",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-138",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "abril",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-139",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "maio",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-140",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "junho",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-141",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "julho",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-142",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "agosto",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-143",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "setembro",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-144",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "outubro",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-145",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "novembro",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-146",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "dezembro",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-147",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "janeiro",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-148",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "fevereiro",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-149",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "março",
      "valor": 23.64,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-150",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "abril",
      "valor": 23.64,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-151",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "maio",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-152",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "junho",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-153",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "julho",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-154",
      "cartao": "Nubank Rafaela",
      "empresa": "Diariamente",
      "empresaNorm": "diariamente",
      "mes": "agosto",
      "valor": 14.56,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-155",
      "cartao": "Nubank Rafaela",
      "empresa": "Exames - São gabriel",
      "empresaNorm": "exames - sao gabriel",
      "mes": "março",
      "valor": 57.39,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-156",
      "cartao": "Nubank Rafaela",
      "empresa": "Exames - São gabriel",
      "empresaNorm": "exames - sao gabriel",
      "mes": "abril",
      "valor": 57.39,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-157",
      "cartao": "Nubank Rafaela",
      "empresa": "Exames - São gabriel",
      "empresaNorm": "exames - sao gabriel",
      "mes": "maio",
      "valor": 57.39,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-158",
      "cartao": "Nubank Rafaela",
      "empresa": "Exames - São gabriel",
      "empresaNorm": "exames - sao gabriel",
      "mes": "junho",
      "valor": 57.39,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-159",
      "cartao": "Nubank Rafaela",
      "empresa": "Youtube",
      "empresaNorm": "youtube",
      "mes": "março",
      "valor": 16.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-160",
      "cartao": "Nubank Rafaela",
      "empresa": "Youtube",
      "empresaNorm": "youtube",
      "mes": "abril",
      "valor": 16.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-161",
      "cartao": "Nubank Rafaela",
      "empresa": "Youtube",
      "empresaNorm": "youtube",
      "mes": "maio",
      "valor": 16.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-162",
      "cartao": "Nubank Rafaela",
      "empresa": "Youtube",
      "empresaNorm": "youtube",
      "mes": "junho",
      "valor": 16.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-163",
      "cartao": "Nubank Rafaela",
      "empresa": "Youtube",
      "empresaNorm": "youtube",
      "mes": "julho",
      "valor": 16.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-164",
      "cartao": "Nubank Rafaela",
      "empresa": "Youtube",
      "empresaNorm": "youtube",
      "mes": "agosto",
      "valor": 16.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-165",
      "cartao": "Nubank Rafaela",
      "empresa": "Shopping Recife",
      "empresaNorm": "shopping recife",
      "mes": "maio",
      "valor": 44.53,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-166",
      "cartao": "Nubank Rafaela",
      "empresa": "Shopping Recife",
      "empresaNorm": "shopping recife",
      "mes": "junho",
      "valor": 44.53,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-167",
      "cartao": "Nubank Rafaela",
      "empresa": "Shopping Recife",
      "empresaNorm": "shopping recife",
      "mes": "julho",
      "valor": 44.53,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-168",
      "cartao": "Nubank Rafaela",
      "empresa": "Shopping Recife",
      "empresaNorm": "shopping recife",
      "mes": "agosto",
      "valor": 44.53,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-169",
      "cartao": "Nubank Rafaela",
      "empresa": "Shopping Recife",
      "empresaNorm": "shopping recife",
      "mes": "setembro",
      "valor": 44.53,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-170",
      "cartao": "Nubank Rafaela",
      "empresa": "Shopping Recife",
      "empresaNorm": "shopping recife",
      "mes": "outubro",
      "valor": 44.53,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-171",
      "cartao": "Nubank Rafaela",
      "empresa": "Shopping Recife",
      "empresaNorm": "shopping recife",
      "mes": "março",
      "valor": 102.47,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-172",
      "cartao": "Nubank Rafaela",
      "empresa": "Alpha co",
      "empresaNorm": "alpha co",
      "mes": "fevereiro",
      "valor": 61.71,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-173",
      "cartao": "Nubank Rafaela",
      "empresa": "Alpha co",
      "empresaNorm": "alpha co",
      "mes": "março",
      "valor": 61.71,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-174",
      "cartao": "Nubank Rafaela",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "dezembro",
      "valor": 17.87,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-175",
      "cartao": "Nubank Rafaela",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "janeiro",
      "valor": 88.91,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-176",
      "cartao": "Nubank Rafaela",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "fevereiro",
      "valor": 71.04,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-177",
      "cartao": "Nubank Rafaela",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "março",
      "valor": 35.14,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-178",
      "cartao": "Nubank Rafaela",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "abril",
      "valor": 35.14,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-179",
      "cartao": "Nubank Rafaela",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "maio",
      "valor": 35.14,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-180",
      "cartao": "Nubank Rafaela",
      "empresa": "Boticário",
      "empresaNorm": "boticario",
      "mes": "junho",
      "valor": 35.14,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-181",
      "cartao": "Nubank Rafaela",
      "empresa": "Farmácia",
      "empresaNorm": "farmacia",
      "mes": "janeiro",
      "valor": 15.99,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-182",
      "cartao": "Nubank Rafaela",
      "empresa": "Farmácia",
      "empresaNorm": "farmacia",
      "mes": "fevereiro",
      "valor": 15.99,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-183",
      "cartao": "Bradesco",
      "empresa": "Iphone",
      "empresaNorm": "iphone",
      "mes": "dezembro",
      "valor": 10.96,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-184",
      "cartao": "Bradesco",
      "empresa": "Iphone",
      "empresaNorm": "iphone",
      "mes": "agosto",
      "valor": 275.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-185",
      "cartao": "Bradesco",
      "empresa": "Iphone",
      "empresaNorm": "iphone",
      "mes": "setembro",
      "valor": 275.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-186",
      "cartao": "Bradesco",
      "empresa": "Iphone",
      "empresaNorm": "iphone",
      "mes": "outubro",
      "valor": 275.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-187",
      "cartao": "Bradesco",
      "empresa": "Iphone",
      "empresaNorm": "iphone",
      "mes": "novembro",
      "valor": 275.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-188",
      "cartao": "Bradesco",
      "empresa": "Iphone",
      "empresaNorm": "iphone",
      "mes": "dezembro",
      "valor": 275.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-189",
      "cartao": "Bradesco",
      "empresa": "Iphone",
      "empresaNorm": "iphone",
      "mes": "maio",
      "valor": 275.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-190",
      "cartao": "Bradesco",
      "empresa": "Iphone",
      "empresaNorm": "iphone",
      "mes": "junho",
      "valor": 275.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-191",
      "cartao": "Bradesco",
      "empresa": "Iphone",
      "empresaNorm": "iphone",
      "mes": "julho",
      "valor": 275.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-192",
      "cartao": "Bradesco",
      "empresa": "OnStar",
      "empresaNorm": "onstar",
      "mes": "maio",
      "valor": 149.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-193",
      "cartao": "Bradesco",
      "empresa": "OnStar",
      "empresaNorm": "onstar",
      "mes": "agosto",
      "valor": 90.0,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-194",
      "cartao": "Bradesco",
      "empresa": "OnStar",
      "empresaNorm": "onstar",
      "mes": "setembro",
      "valor": 90.0,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-195",
      "cartao": "Bradesco",
      "empresa": "OnStar",
      "empresaNorm": "onstar",
      "mes": "outubro",
      "valor": 90.0,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-196",
      "cartao": "Bradesco",
      "empresa": "OnStar",
      "empresaNorm": "onstar",
      "mes": "novembro",
      "valor": 90.0,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-197",
      "cartao": "Bradesco",
      "empresa": "OnStar",
      "empresaNorm": "onstar",
      "mes": "dezembro",
      "valor": 90.0,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-198",
      "cartao": "Bradesco",
      "empresa": "Icloud",
      "empresaNorm": "icloud",
      "mes": "maio",
      "valor": 5.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-199",
      "cartao": "Bradesco",
      "empresa": "Icloud",
      "empresaNorm": "icloud",
      "mes": "junho",
      "valor": 5.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-200",
      "cartao": "Bradesco",
      "empresa": "Icloud",
      "empresaNorm": "icloud",
      "mes": "julho",
      "valor": 5.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-201",
      "cartao": "Bradesco",
      "empresa": "Icloud",
      "empresaNorm": "icloud",
      "mes": "agosto",
      "valor": 5.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-202",
      "cartao": "Bradesco",
      "empresa": "Icloud",
      "empresaNorm": "icloud",
      "mes": "setembro",
      "valor": 5.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-203",
      "cartao": "Bradesco",
      "empresa": "Icloud",
      "empresaNorm": "icloud",
      "mes": "outubro",
      "valor": 5.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-204",
      "cartao": "Bradesco",
      "empresa": "Icloud",
      "empresaNorm": "icloud",
      "mes": "novembro",
      "valor": 5.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-205",
      "cartao": "Bradesco",
      "empresa": "Icloud",
      "empresaNorm": "icloud",
      "mes": "dezembro",
      "valor": 5.9,
      "categoria": "Assinaturas",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-206",
      "cartao": "Bradesco",
      "empresa": "Iphone - Rafaela",
      "empresaNorm": "iphone - rafaela",
      "mes": "maio",
      "valor": 515.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-207",
      "cartao": "Bradesco",
      "empresa": "Iphone - Rafaela",
      "empresaNorm": "iphone - rafaela",
      "mes": "junho",
      "valor": 515.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-208",
      "cartao": "Bradesco",
      "empresa": "Iphone - Rafaela",
      "empresaNorm": "iphone - rafaela",
      "mes": "julho",
      "valor": 515.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-209",
      "cartao": "Bradesco",
      "empresa": "Iphone - Rafaela",
      "empresaNorm": "iphone - rafaela",
      "mes": "agosto",
      "valor": 515.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-210",
      "cartao": "Bradesco",
      "empresa": "Iphone - Rafaela",
      "empresaNorm": "iphone - rafaela",
      "mes": "setembro",
      "valor": 515.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-211",
      "cartao": "Bradesco",
      "empresa": "Iphone - Rafaela",
      "empresaNorm": "iphone - rafaela",
      "mes": "outubro",
      "valor": 515.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-212",
      "cartao": "Bradesco",
      "empresa": "Iphone - Rafaela",
      "empresaNorm": "iphone - rafaela",
      "mes": "novembro",
      "valor": 515.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-213",
      "cartao": "Bradesco",
      "empresa": "Iphone - Rafaela",
      "empresaNorm": "iphone - rafaela",
      "mes": "dezembro",
      "valor": 515.0,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-214",
      "cartao": "Bradesco",
      "empresa": "Perfume",
      "empresaNorm": "perfume",
      "mes": "dezembro",
      "valor": 49.07,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-215",
      "cartao": "Bradesco",
      "empresa": "Perfume",
      "empresaNorm": "perfume",
      "mes": "julho",
      "valor": 22.89,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-216",
      "cartao": "Bradesco",
      "empresa": "Perfume",
      "empresaNorm": "perfume",
      "mes": "agosto",
      "valor": 12.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-217",
      "cartao": "Bradesco",
      "empresa": "Perfume",
      "empresaNorm": "perfume",
      "mes": "setembro",
      "valor": 12.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-218",
      "cartao": "Bradesco",
      "empresa": "Perfume",
      "empresaNorm": "perfume",
      "mes": "outubro",
      "valor": 12.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-219",
      "cartao": "Bradesco",
      "empresa": "Perfume",
      "empresaNorm": "perfume",
      "mes": "novembro",
      "valor": 12.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-220",
      "cartao": "Bradesco",
      "empresa": "Perfume",
      "empresaNorm": "perfume",
      "mes": "dezembro",
      "valor": 12.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-221",
      "cartao": "Bradesco",
      "empresa": "Perfume",
      "empresaNorm": "perfume",
      "mes": "maio",
      "valor": 12.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-222",
      "cartao": "Bradesco",
      "empresa": "Perfume",
      "empresaNorm": "perfume",
      "mes": "junho",
      "valor": 12.9,
      "categoria": "Outros",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-223",
      "cartao": "Itaucard Felipe",
      "empresa": "Whey",
      "empresaNorm": "whey",
      "mes": "maio",
      "valor": 93.49,
      "categoria": "Saúde/Academia",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-224",
      "cartao": "Itaucard Felipe",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "maio",
      "valor": 13.9,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-225",
      "cartao": "Itaucard Felipe",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "junho",
      "valor": 13.9,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-226",
      "cartao": "Itaucard Felipe",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "julho",
      "valor": 13.9,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-227",
      "cartao": "Itaucard Felipe",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "maio",
      "valor": 8.66,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-228",
      "cartao": "Itaucard Felipe",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "junho",
      "valor": 8.66,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-229",
      "cartao": "Itaucard Felipe",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "julho",
      "valor": 8.66,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-230",
      "cartao": "Itaucard Felipe",
      "empresa": "Amazon",
      "empresaNorm": "amazon",
      "mes": "agosto",
      "valor": 8.66,
      "categoria": "Compras",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-231",
      "cartao": "Itaucard Felipe",
      "empresa": "Moto",
      "empresaNorm": "moto",
      "mes": "maio",
      "valor": 1945.0,
      "categoria": "Transporte",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-232",
      "cartao": "Itaucard Felipe",
      "empresa": "Moto",
      "empresaNorm": "moto",
      "mes": "junho",
      "valor": 1945.0,
      "categoria": "Transporte",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    },
    {
      "id": "import-233",
      "cartao": "Itaucard Felipe",
      "empresa": "Moto",
      "empresaNorm": "moto",
      "mes": "julho",
      "valor": 1945.0,
      "categoria": "Transporte",
      "data": "",
      "parcela": "importado",
      "meio": "Cartão",
      "origem": "planilha"
    }
  ],
  "cartoes": [
    {
      "nome": "Nubank Felipe"
    },
    {
      "nome": "Nubank Rafaela"
    },
    {
      "nome": "Bradesco"
    },
    {
      "nome": "Itaucard Felipe"
    }
  ],
  "feira": [
    {
      "produto": "salgadinhos",
      "grupo": "Feira",
      "preco": 4.29,
      "quantidade": 8.0,
      "total": 34.32
    },
    {
      "produto": "flocão",
      "grupo": "Feira",
      "preco": 2.29,
      "quantidade": 14.0,
      "total": 32.06
    },
    {
      "produto": "feijão carioca",
      "grupo": "Feira",
      "preco": 6.48,
      "quantidade": 2.0,
      "total": 12.96
    },
    {
      "produto": "feijão preto",
      "grupo": "Feira",
      "preco": 9.5,
      "quantidade": 2.0,
      "total": 19.0
    },
    {
      "produto": "arroz",
      "grupo": "Feira",
      "preco": 5.85,
      "quantidade": 3.0,
      "total": 17.55
    },
    {
      "produto": "macarrão",
      "grupo": "Feira",
      "preco": 2.28,
      "quantidade": 4.0,
      "total": 9.12
    },
    {
      "produto": "peixe",
      "grupo": "Feira",
      "preco": 21.59,
      "quantidade": 4.0,
      "total": 86.36
    },
    {
      "produto": "coca",
      "grupo": "Feira",
      "preco": 6.79,
      "quantidade": 4.0,
      "total": 27.16
    },
    {
      "produto": "papel higiênico",
      "grupo": "Feira",
      "preco": 17.48,
      "quantidade": 1.0,
      "total": 17.48
    },
    {
      "produto": "Detergente",
      "grupo": "Feira",
      "preco": 2.18,
      "quantidade": 12.0,
      "total": 26.16
    },
    {
      "produto": "Água sanitária",
      "grupo": "Feira",
      "preco": 1.99,
      "quantidade": 4.0,
      "total": 7.96
    },
    {
      "produto": "Sabão em pó",
      "grupo": "Feira",
      "preco": 7.49,
      "quantidade": 4.0,
      "total": 29.96
    },
    {
      "produto": "Esponja amarela",
      "grupo": "Feira",
      "preco": 3.69,
      "quantidade": 2.0,
      "total": 7.38
    },
    {
      "produto": "Esponja azul",
      "grupo": "Feira",
      "preco": 3.99,
      "quantidade": 2.0,
      "total": 7.98
    },
    {
      "produto": "atum",
      "grupo": "Feira",
      "preco": 7.89,
      "quantidade": 2.0,
      "total": 15.78
    },
    {
      "produto": "kapo uva",
      "grupo": "Feira",
      "preco": 12.99,
      "quantidade": 4.0,
      "total": 51.96
    },
    {
      "produto": "kapo morango",
      "grupo": "Feira",
      "preco": 2.38,
      "quantidade": 30.0,
      "total": 71.4
    },
    {
      "produto": "danone",
      "grupo": "Feira",
      "preco": 2.99,
      "quantidade": 30.0,
      "total": 89.7
    },
    {
      "produto": "filtro de café",
      "grupo": "Feira",
      "preco": 4.48,
      "quantidade": 1.0,
      "total": 4.48
    },
    {
      "produto": "amaciante",
      "grupo": "Feira",
      "preco": 24.98,
      "quantidade": 1.0,
      "total": 24.98
    },
    {
      "produto": "margarina",
      "grupo": "Feira",
      "preco": 4.68,
      "quantidade": 2.0,
      "total": 9.36
    },
    {
      "produto": "sabonete",
      "grupo": "Feira",
      "preco": 2.07,
      "quantidade": 16.0,
      "total": 33.16
    },
    {
      "produto": "cacau",
      "grupo": "Feira",
      "preco": 18.0,
      "quantidade": 1.0,
      "total": 18.0
    },
    {
      "produto": "azeite",
      "grupo": "Feira",
      "preco": 28.0,
      "quantidade": 1.0,
      "total": 28.0
    },
    {
      "produto": "desodorante",
      "grupo": "Feira",
      "preco": 20.0,
      "quantidade": 1.0,
      "total": 20.0
    },
    {
      "produto": "aveia",
      "grupo": "Feira",
      "preco": 11.48,
      "quantidade": 2.0,
      "total": 22.96
    },
    {
      "produto": "trigo",
      "grupo": "Feira",
      "preco": 6.0,
      "quantidade": 1.0,
      "total": 6.0
    },
    {
      "produto": "oleo",
      "grupo": "Feira",
      "preco": 8.99,
      "quantidade": 2.0,
      "total": 17.98
    },
    {
      "produto": "papel toalha",
      "grupo": "Feira",
      "preco": 4.3,
      "quantidade": 1.0,
      "total": 4.3
    },
    {
      "produto": "desinfetante",
      "grupo": "Feira",
      "preco": 4.5,
      "quantidade": 3.0,
      "total": 13.5
    },
    {
      "produto": "Frutas",
      "grupo": "Feira",
      "preco": 70.0,
      "quantidade": 4.0,
      "total": 280.0
    },
    {
      "produto": "ovo",
      "grupo": "Feira",
      "preco": 33.96,
      "quantidade": 4.0,
      "total": 135.84
    },
    {
      "produto": "pão",
      "grupo": "Feira",
      "preco": 6.79,
      "quantidade": 4.0,
      "total": 27.16
    },
    {
      "produto": "Carne",
      "grupo": "Feira",
      "preco": 150.0,
      "quantidade": 4.0,
      "total": 600.0
    },
    {
      "produto": "Goma",
      "grupo": "Feira",
      "preco": 15.0,
      "quantidade": 4.0,
      "total": 60.0
    },
    {
      "produto": "charque",
      "grupo": "Feira",
      "preco": 45.0,
      "quantidade": 4.0,
      "total": 180.0
    }
  ],
  "config": {
    "orcamentoFeira": 2050.01,
    "orcamentoCombustivel": 1200,
    "familyKeyName": "CAMARGO-2026"
  },
  "categoriaRules": [
    [
      "Feira",
      [
        "assai",
        "atacadao",
        "atacarejo",
        "bom dia",
        "supermercado",
        "mercado",
        "carrefour",
        "hortifruti",
        "padaria",
        "feira",
        "grocery"
      ]
    ],
    [
      "Combustível",
      [
        "posto",
        "shell",
        "ipiranga",
        "petrobras",
        "br ",
        "combust",
        "gasolina",
        "etanol",
        "diesel"
      ]
    ],
    [
      "Saúde/Academia",
      [
        "gympass",
        "academia",
        "natacao",
        "natação",
        "unimed",
        "cerpe",
        "farm",
        "drog",
        "clinica",
        "medic",
        "whey",
        "osteopatia",
        "odont",
        "consulta"
      ]
    ],
    [
      "Assinaturas",
      [
        "icloud",
        "onstar",
        "spotify",
        "netflix",
        "prime",
        "google",
        "apple",
        "youtube",
        "assinatura"
      ]
    ],
    [
      "Educação",
      [
        "escola",
        "farda",
        "livro",
        "material",
        "curso",
        "yuri"
      ]
    ],
    [
      "Lazer",
      [
        "game",
        "cinema",
        "restaurante",
        "ifood",
        "lanche",
        "pizza",
        "parque"
      ]
    ],
    [
      "Transporte",
      [
        "uber",
        "99",
        "estacionamento",
        "pedagio",
        "moto",
        "seguro da moto"
      ]
    ],
    [
      "Compras",
      [
        "amazon",
        "mercado livre",
        "shopee",
        "shein",
        "natura",
        "iphone",
        "magalu",
        "loja",
        "bradesco"
      ]
    ]
  ]
};
