-- Finanças Família - Supabase seguro por chave familiar via RPC
-- Não cria políticas abertas. O acesso direto às tabelas permanece bloqueado por RLS.

create table if not exists family_states (
  family_key_hash text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table family_states enable row level security;

-- Não criar políticas SELECT/INSERT/UPDATE abertas para anon.
-- O frontend usa somente as funções abaixo.

create extension if not exists pgcrypto;

create or replace function family_hash_key(p_family_key text)
returns text
language sql
stable
as $$
  select encode(digest(coalesce(p_family_key,'') || ':financas-familia-v26-5', 'sha256'), 'hex');
$$;

create or replace function family_save_state(p_family_key text, p_payload jsonb)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_family_key is null or length(trim(p_family_key)) < 8 then
    raise exception 'Código familiar inválido';
  end if;

  insert into family_states (family_key_hash, payload, updated_at)
  values (family_hash_key(p_family_key), p_payload, now())
  on conflict (family_key_hash)
  do update set payload = excluded.payload, updated_at = now();

  return true;
end;
$$;

create or replace function family_load_state(p_family_key text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if p_family_key is null or length(trim(p_family_key)) < 8 then
    raise exception 'Código familiar inválido';
  end if;

  select payload into result
  from family_states
  where family_key_hash = family_hash_key(p_family_key);

  return coalesce(result, '{}'::jsonb);
end;
$$;

grant execute on function family_save_state(text, jsonb) to anon, authenticated;
grant execute on function family_load_state(text) to anon, authenticated;


-- Payload: compras, config, fixas, orcamento, feira, variaveis, history, updated_by, device, lastUpdated.


-- Histórico próprio - V26.5
create table if not exists public.family_history (
  id bigint generated by default as identity primary key,
  family_hash text not null,
  event jsonb not null,
  created_at timestamptz default now()
);

alter table public.family_history enable row level security;

create or replace function public.family_append_history(p_family_key text, p_events jsonb)
returns void
language plpgsql
security definer
as $$
declare
  fh text;
  ev jsonb;
begin
  fh := encode(digest(p_family_key || ':financas-familia-v26-5', 'sha256'), 'hex');
  for ev in select * from jsonb_array_elements(p_events)
  loop
    insert into public.family_history(family_hash,event) values (fh,ev);
  end loop;
end;
$$;

create or replace function public.family_load_history(p_family_key text)
returns jsonb
language plpgsql
security definer
as $$
declare
  fh text;
  result jsonb;
begin
  fh := encode(digest(p_family_key || ':financas-familia-v26-5', 'sha256'), 'hex');
  select coalesce(jsonb_agg(event order by created_at desc), '[]'::jsonb)
  into result
  from (
    select event, created_at
    from public.family_history
    where family_hash = fh
    order by created_at desc
    limit 250
  ) h;
  return result;
end;
$$;


-- Grants V26.5
grant execute on function public.family_save_state(text,jsonb) to anon, authenticated;
grant execute on function public.family_load_state(text) to anon, authenticated;
grant execute on function public.family_append_history(text,jsonb) to anon, authenticated;
grant execute on function public.family_load_history(text) to anon, authenticated;


-- Histórico paginado e pesquisável
create or replace function public.family_load_history_paged(
  p_family_key text,
  p_limit integer default 50,
  p_offset integer default 0,
  p_search text default ''
)
returns jsonb
language plpgsql
security definer
as $$
declare
  fh text;
  result jsonb;
begin
  -- Mantém o mesmo sal da versão vigente do histórico para não quebrar dados existentes.
  fh := encode(digest(p_family_key || ':financas-familia-v26-5', 'sha256'), 'hex');

  select coalesce(jsonb_agg(event order by created_at desc), '[]'::jsonb)
  into result
  from (
    select event, created_at
    from public.family_history
    where family_hash = fh
      and (
        coalesce(p_search,'') = ''
        or lower(event::text) like '%' || lower(p_search) || '%'
      )
    order by created_at desc
    limit greatest(1, p_limit)
    offset greatest(0, p_offset)
  ) h;

  return result;
end;
$$;

grant execute on function public.family_load_history_paged(text,integer,integer,text) to anon, authenticated;
